version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: marketplace-db
    environment:
      POSTGRES_DB: marketplacedb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_market:/var/lib/postgresql/data

volumes:
  postgres_data_market: